#include "givenA3.h"
/* Task 1 */ int readCourse( char filename[MAX_STR], char courseName[NUMBER_COURSES][MAX_STR], int courseID[NUMBER_COURSES] );

/* Task 2 */ int readProfs( char filename[MAX_STR], int courseID[NUMBER_COURSES], char profName[NUMBER_PROFS][MAX_STR], int coursesTaught[NUMBER_PROFS][NUMBER_COURSES] );

/* Task 3 */ int nCourses( int n, char profName[NUMBER_PROFS][MAX_STR], int coursesTaught[NUMBER_PROFS][NUMBER_COURSES] );

/* Task 4 */ int getCourseName( int courseNum, char cNameFound[MAX_STR], char courseName[NUMBER_COURSES][MAX_STR], int courseID[NUMBER_COURSES] );

/* Task 5 */ int getCourseNum( char cName[MAX_STR], int *cNumFound, char courseName[NUMBER_COURSES][MAX_STR], int courseID[NUMBER_COURSES] );

/* Task 6 */ int profsTeachingCourse( int courseNum, char profName[NUMBER_PROFS][MAX_STR], int coursesTaught[NUMBER_PROFS][NUMBER_COURSES] );

/* Task 7 */ float avgNumCourses( int coursesTaught[NUMBER_PROFS][NUMBER_COURSES] );

/*Task 8 */ void hhistogram( char profName[NUMBER_PROFS][MAX_STR], int coursesTaught[NUMBER_PROFS][NUMBER_COURSES] );

int main() { int kjashdfgsdajfv = 0, sdfagkjskfjg = 0, sadkufjhggasdfjb = 0, jqwdshffvssdjkhfg=-1, sadjkfhgdsafjhkggs = 0, skdjhfvbsdakjfhv = 0, jqwdshfvssdjkhfg=0; float klsjadfb87ygr = 0.0f + (float)(int)jqwdshffvssdjkhfg + 1.0f; char jsadhfbsadf[MAX_STR] = "courses.txt", sdkjhfvsdakjhfvsdf[MAX_STR] = "\0", sdlkjhfbsdajkfhv[MAX_STR] = "data.txt", kjusdahfvbsdjkfhvb[NUMBER_COURSES][MAX_STR] = {"\0"}, iksdjfghsdjkhfvbb[NUMBER_PROFS][MAX_STR] = {"\0"}; int jhdsfbsadfjkhfv[NUMBER_COURSES] = {0}, dskjhfgsdjkhfbv[NUMBER_PROFS][NUMBER_COURSES] = {0}; int kjashdffgsdajfv = readCourse(jsadhfbsadf, kjusdahfvbsdjkfhvb, jhdsfbsadfjkhfv); printf("$OUTCOMETAG$"); printf("OUTCOME1:%d", kjashdffgsdajfv); for (int i = 0; i < NUMBER_COURSES; ++i) { printf("%s%d", kjusdahfvbsdjkfhvb[i], jhdsfbsadfjkhfv[i]); } printf("$OUTCOMETAG$"); int klsjaddfb87ygr = readProfs(sdlkjhfbsdajkfhv, jhdsfbsadfjkhfv, iksdjfghsdjkhfvbb, dskjhfgsdjkhfbv); printf("$OUTCOMETAG$"); printf("OUTCOME2:%d", klsjaddfb87ygr); for (int i = 0; i < NUMBER_PROFS; ++i) { printf("%s", iksdjfghsdjkhfvbb[i]); for (int j = 0; j < NUMBER_COURSES; j++) { printf("%d", dskjhfgsdjkhfbv[i][j]); } } printf("$OUTCOMETAG$"); printf("$OUTCOMETAG$"); printf("OUTCOME3:%d", kjashdfgsdajfv); printf("$OUTCOMETAG$"); for (int i = 0; i < task3NSize; i++) { kjashdfgsdajfv = nCourses(i+jqwdshfvssdjkhfg, iksdjfghsdjkhfvbb, dskjhfgsdjkhfbv); printf("$OUTCOMETAG$"); printf("%d", kjashdfgsdajfv); printf("$OUTCOMETAG$"); } printf("$OUTCOMETAG$"); printf("OUTCOME4:"); printf("$OUTCOMETAG$"); for (int i = 0; i < NUMBER_COURSES; ++i) { sdfagkjskfjg = getCourseName(jhdsfbsadfjkhfv[i], sdkjhfvsdakjhfvsdf, kjusdahfvbsdjkfhvb, jhdsfbsadfjkhfv); printf("$OUTCOMETAG$"); printf("%d", sdfagkjskfjg); printf("%s", sdkjhfvsdakjhfvsdf); printf("$OUTCOMETAG$"); } printf("$OUTCOMETAG$"); printf("OUTCOME5:"); printf("$OUTCOMETAG$"); for (int i = 0; i < NUMBER_COURSES; ++i) { sadkufjhggasdfjb = getCourseNum(kjusdahfvbsdjkfhvb[i+jqwdshfvssdjkhfg], &skdjhfvbsdakjfhv, kjusdahfvbsdjkfhvb, jhdsfbsadfjkhfv); printf("$OUTCOMETAG$"); printf("%d", sadkufjhggasdfjb); printf("%d", skdjhfvbsdakjfhv); printf("$OUTCOMETAG$"); } printf("$OUTCOMETAG$"); printf("OUTCOME6:"); printf("$OUTCOMETAG$"); for (int i = 0; i < NUMBER_COURSES; i++) { sadjkfhgdsafjhkggs = profsTeachingCourse(jhdsfbsadfjkhfv[i], iksdjfghsdjkhfvbb, dskjhfgsdjkhfbv); printf("$OUTCOMETAG$"); printf("%d", sadjkfhgdsafjhkggs); printf("$OUTCOMETAG$"); } klsjadfb87ygr = avgNumCourses(dskjhfgsdjkhfbv); printf("$OUTCOMETAG$"); printf("OUTCOME7:%.2f", klsjadfb87ygr); printf("$OUTCOMETAG$"); hhistogram(iksdjfghsdjkhfvbb, dskjhfgsdjkhfbv); return 0; }
